/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function cropVideo(cropStart: number, cropEnd: number) {
    return invoke()<string>("crop_video", { cropStart,cropEnd })
}

export function selectVideo() {
    return invoke()<string>("select_video")
}


